//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.23 at 09:21:56 PM EDT 
//

package com.topografix.gpx._1._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * 
 * Information about the copyright holder and any license governing use of this
 * file. By linking to an appropriate license, you may place your data into the
 * public domain or grant additional usage rights.
 * 
 * 
 * <p>
 * Java class for copyrightType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;copyrightType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;year&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}gYear&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;license&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anyURI&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;author&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "copyrightType", propOrder = { "year", "license" })
public class CopyrightType {

    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar year;
    @XmlSchemaType(name = "anyURI")
    protected String license;
    @XmlAttribute(required = true)
    protected String author;

    /**
     * Gets the value of the year property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getYear() {
	return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setYear(XMLGregorianCalendar value) {
	this.year = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLicense() {
	return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLicense(String value) {
	this.license = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAuthor() {
	return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAuthor(String value) {
	this.author = value;
    }

}
