//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.23 at 09:21:56 PM EDT 
//

package com.topografix.gpx._1._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * A Track Segment holds a list of Track Points which are logically connected in
 * order. To represent a single GPS track where GPS reception was lost, or the
 * GPS receiver was turned off, start a new Track Segment for each continuous
 * span of track data.
 * 
 * 
 * <p>
 * Java class for trksegType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;trksegType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;trkpt&quot; type=&quot;{http://www.topografix.com/GPX/1/1}wptType&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;extensions&quot; type=&quot;{http://www.topografix.com/GPX/1/1}extensionsType&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trksegType", propOrder = { "trkpt", "extensions" })
public class TrksegType {

    protected List<WptType> trkpt;
    protected ExtensionsType extensions;

    /**
     * Gets the value of the trkpt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the trkpt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTrkpt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link WptType }
     * 
     * 
     */
    public List<WptType> getTrkpt() {
	if (trkpt == null) {
	    trkpt = new ArrayList<WptType>();
	}
	return this.trkpt;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return possible object is {@link ExtensionsType }
     * 
     */
    public ExtensionsType getExtensions() {
	return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *            allowed object is {@link ExtensionsType }
     * 
     */
    public void setExtensions(ExtensionsType value) {
	this.extensions = value;
    }

}
