//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.25 at 07:37:16 AM EDT 
//

package com.garmin.xmlschemas.gpxextensions.v3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for AutoroutePoint_t complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;AutoroutePoint_t&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Subclass&quot; type=&quot;{http://www.garmin.com/xmlschemas/GpxExtensions/v3}Subclass_t&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;lat&quot; use=&quot;required&quot; type=&quot;{http://www.garmin.com/xmlschemas/GpxExtensions/v3}Latitude_t&quot; /&gt;
 *       &lt;attribute name=&quot;lon&quot; use=&quot;required&quot; type=&quot;{http://www.garmin.com/xmlschemas/GpxExtensions/v3}Longitude_t&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutoroutePoint_t", propOrder = { "subclass" })
public class AutoroutePointT {

    @XmlElement(name = "Subclass", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] subclass;
    @XmlAttribute(required = true)
    protected BigDecimal lat;
    @XmlAttribute(required = true)
    protected BigDecimal lon;

    /**
     * Gets the value of the subclass property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public byte[] getSubclass() {
	return subclass;
    }

    /**
     * Sets the value of the subclass property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSubclass(byte[] value) {
	this.subclass = ((byte[]) value);
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getLat() {
	return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setLat(BigDecimal value) {
	this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getLon() {
	return lon;
    }

    /**
     * Sets the value of the lon property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setLon(BigDecimal value) {
	this.lon = value;
    }

}
