//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.25 at 07:37:16 AM EDT 
//

package com.garmin.xmlschemas.gpxextensions.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DisplayMode_t.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;DisplayMode_t&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}token&quot;&gt;
 *     &lt;enumeration value=&quot;SymbolOnly&quot;/&gt;
 *     &lt;enumeration value=&quot;SymbolAndName&quot;/&gt;
 *     &lt;enumeration value=&quot;SymbolAndDescription&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DisplayMode_t")
@XmlEnum
public enum DisplayModeT {

    @XmlEnumValue("SymbolOnly")
    SYMBOL_ONLY("SymbolOnly"), @XmlEnumValue("SymbolAndName")
    SYMBOL_AND_NAME("SymbolAndName"), @XmlEnumValue("SymbolAndDescription")
    SYMBOL_AND_DESCRIPTION("SymbolAndDescription");
    private final String value;

    DisplayModeT(String v) {
	value = v;
    }

    public String value() {
	return value;
    }

    public static DisplayModeT fromValue(String v) {
	for (DisplayModeT c : DisplayModeT.values()) {
	    if (c.value.equals(v)) {
		return c;
	    }
	}
	throw new IllegalArgumentException(v);
    }

}
