//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.25 at 07:37:16 AM EDT 
//

package com.garmin.xmlschemas.gpxextensions.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * This type contains data fields available in Garmin GDB routes that cannot be
 * represented in routes in GPX 1.1 instances.
 * 
 * 
 * <p>
 * Java class for RoutePointExtension_t complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;RoutePointExtension_t&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Subclass&quot; type=&quot;{http://www.garmin.com/xmlschemas/GpxExtensions/v3}Subclass_t&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;rpt&quot; type=&quot;{http://www.garmin.com/xmlschemas/GpxExtensions/v3}AutoroutePoint_t&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;Extensions&quot; type=&quot;{http://www.garmin.com/xmlschemas/GpxExtensions/v3}Extensions_t&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoutePointExtension_t", propOrder = { "subclass", "rpt", "extensions" })
public class RoutePointExtensionT {

    @XmlElement(name = "Subclass", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] subclass;
    protected List<AutoroutePointT> rpt;
    @XmlElement(name = "Extensions")
    protected ExtensionsT extensions;

    /**
     * Gets the value of the subclass property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public byte[] getSubclass() {
	return subclass;
    }

    /**
     * Sets the value of the subclass property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSubclass(byte[] value) {
	this.subclass = ((byte[]) value);
    }

    /**
     * Gets the value of the rpt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the rpt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRpt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AutoroutePointT }
     * 
     * 
     */
    public List<AutoroutePointT> getRpt() {
	if (rpt == null) {
	    rpt = new ArrayList<AutoroutePointT>();
	}
	return this.rpt;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return possible object is {@link ExtensionsT }
     * 
     */
    public ExtensionsT getExtensions() {
	return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *            allowed object is {@link ExtensionsT }
     * 
     */
    public void setExtensions(ExtensionsT value) {
	this.extensions = value;
    }

}
